plugins {
    id 'io.nextflow.nextflow-plugin' version '1.0.0-beta.15'
}

version = '0.1.0'



nextflowPlugin {
    nextflowVersion = '25.10.0'

    provider = 'nextflow'
    className = 'nextflow.plugin.NfTrinoPlugin'
    generateSpec = false
    extensionPoints = [
        'nextflow.sql.ChannelSqlExtension'
    ]

}

repositories {
    exclusiveContent {
        forRepository {
            ivy {
                name = 'awsAthenaJdbcDownloads'
                url = uri('https://downloads.athena.us-east-1.amazonaws.com/drivers/JDBC')
                patternLayout {
                    artifact '[revision]/[artifact]-[revision]-with-dependencies.[ext]'
                }
                metadataSources {
                    artifact()
                }
            }
        }
        filter {
            includeGroup 'software.amazon.athena'
        }
    }
}

configurations {
    athenaJdbc
    api.extendsFrom athenaJdbc
}

dependencies {
    api("org.apache.groovy:groovy-sql:4.0.26") { transitive = false }
    // FIXME: Upgrade when https://github.com/nextflow-io/nf-sqldb/issues/33 is resolved.
    api("io.nextflow:nf-sqldb:0.7.0") { transitive = false }
    // H2 backs the deterministic no-service smoke workflow.
    api("com.h2database:h2:2.2.224") { transitive = false }
    
    // Trino JDBC driver from Maven Central
    // Reference https://trino.io/docs/current/client/jdbc.html
    api("io.trino:trino-jdbc:476")
    
    // AWS Athena JDBC driver from the official AWS download repository
    // Reference https://docs.aws.amazon.com/athena/latest/ug/jdbc-v3-driver.html
    athenaJdbc("software.amazon.athena:athena-jdbc:3.8.0") { transitive = false }
    
    // Testcontainers for integration testing
    testImplementation("org.testcontainers:testcontainers:1.20.0")
    testImplementation("org.testcontainers:trino:1.20.0")
    testImplementation("org.testcontainers:spock:1.20.0")
}

test {
    useJUnitPlatform {
        if (!project.hasProperty('integration'))
            excludeTags 'Integration'
    }
}

task verifyAthenaDriverSignature(type: Exec) {
    inputs.files(configurations.athenaJdbc)
    doFirst {
        commandLine "${System.getProperty('java.home')}/bin/jarsigner",
            '-verify',
            '-strict',
            configurations.athenaJdbc.singleFile
    }
}

project.compileGroovy.dependsOn('verifyAthenaDriverSignature')
