plugins {
    id 'io.nextflow.nextflow-plugin' version '0.0.1-alpha4'
}

version = '0.1.0'

nextflowPlugin {
    nextflowVersion = '24.10.0'

    provider = 'nextflow'
    className = 'nextflow.plugin.NfTrinoPlugin'
    extensionPoints = [
        'nextflow.plugin.NfTrinoExtension',
        'nextflow.plugin.NfTrinoFactory'
    ]

    publishing {
        registry {
            url = 'https://nf-plugins-registry.dev-tower.net/api'
            authToken = project.findProperty('pluginRegistry.accessToken')
        }
    }
}
